try:
    import utils.main
    utils.main
except Exception as e:
    print(f'The error {e} has happenned!')